'use client'

import { useState } from 'react';

export default function Home() {
  const [prompt, setPrompt] = useState('');
  const [image, setImage] = useState('');
  const [aspectRatio, setAspectRatio] = useState('1:1');

  const generateImage = (e) => {
    e.preventDefault();

    let width = 1024;
    let height = 1024;

    if (aspectRatio === '9:16') {
      width = 576; 
      height = 1024;
    } else if (aspectRatio === '16:9') {
      width = 1024;
      height = 576;
    }
    
    // Perhatikan: prompt harus dienkode untuk URL
    const encodedPrompt = encodeURIComponent(prompt);
    
    // URL API yang dinamis
    const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&model=gptimage&quality=hd&enhance=true&nologo=true`;
    
    setImage(imageUrl);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4">
      <h1 className="text-4xl font-bold mb-8 text-center text-gray-800">
        AI Image Generator
      </h1>

      <form onSubmit={generateImage} className="w-full max-w-lg mb-8">
        <div className="mb-4">
          <label htmlFor="prompt" className="block text-gray-700 text-sm font-bold mb-2">
            Enter your prompt:
          </label>
          <input
            id="prompt"
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            placeholder="A futuristic city in the style of cyberpunk..."
          />
        </div>

        <div className="mb-6">
          <label className="block text-gray-700 text-sm font-bold mb-2">
            Aspect Ratio:
          </label>
          <div className="flex items-center space-x-4">
            <label className="inline-flex items-center">
              <input
                type="radio"
                name="aspectRatio"
                value="1:1"
                checked={aspectRatio === '1:1'}
                onChange={(e) => setAspectRatio(e.target.value)}
                className="form-radio"
              />
              <span className="ml-2 text-gray-700">1:1 (Square)</span>
            </label>
            <label className="inline-flex items-center">
              <input
                type="radio"
                name="aspectRatio"
                value="9:16"
                checked={aspectRatio === '9:16'}
                onChange={(e) => setAspectRatio(e.target.value)}
                className="form-radio"
              />
              <span className="ml-2 text-gray-700">9:16 (Portrait)</span>
            </label>
            <label className="inline-flex items-center">
              <input
                type="radio"
                name="aspectRatio"
                value="16:9"
                checked={aspectRatio === '16:9'}
                onChange={(e) => setAspectRatio(e.target.value)}
                className="form-radio"
              />
              <span className="ml-2 text-gray-700">16:9 (Landscape)</span>
            </label>
          </div>
        </div>

        <button
          type="submit"
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full"
        >
          Generate Image
        </button>
      </form>

      {image && (
        <div className="mt-8 p-4 bg-white rounded-lg shadow-lg">
          <h2 className="text-xl font-semibold mb-4 text-center">
            Generated Image
          </h2>
          <img 
            src={image} 
            alt="Generated by AI" 
            className="rounded-lg max-w-full h-auto"
          />
        </div>
      )}
    </div>
  );
}